In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
indep=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dep=dataset[['charges']]

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error','poisson','friedman_mse'],'max_features':['auto','sqrt','log2'],'splitter':['best','random']}


grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(indep, dep)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'poisson',
                                       'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [10]:
re=grid.cv_results_
print("The R_score value for the best para parameter {}:".format(grid.best_params_))

The R_score value for the best para parameter {'criterion': 'squared_error', 'max_features': 'sqrt', 'splitter': 'best'}:

In [11]:
table=pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.018831,0.006212,0.006251,0.007656,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",0.730546,0.655809,0.735685,0.738151,0.654652,0.702969,0.039057,2
1,0.015106,0.008247,0.007651,0.006996,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",0.692842,0.685034,0.676165,0.728009,0.724418,0.701294,0.021051,3
2,0.011156,0.005881,0.006251,0.007656,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.738202,0.625052,0.767228,0.749241,0.744688,0.724882,0.050838,1
3,0.009534,0.012681,0.032392,0.047172,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.618649,0.635134,0.739061,0.652364,0.733873,0.675816,0.050683,8
4,0.029410,0.035888,0.018850,0.037700,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.715266,0.540372,0.685458,0.718094,0.763155,0.684469,0.076205,7
5,0.003125,0.006251,0.050227,0.049087,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.700318,0.633946,0.551564,0.675772,0.601396,0.632599,0.052900,13
6,0.062993,0.055222,0.068214,0.046531,poisson,auto,best,"{'criterion': 'poisson', 'max_features': 'auto...",0.686792,0.638715,0.736632,0.745787,0.690336,0.699652,0.038630,4
7,0.023065,0.043426,0.030311,0.037670,poisson,auto,random,"{'criterion': 'poisson', 'max_features': 'auto...",0.685871,0.572773,0.524886,0.634974,0.656186,0.614938,0.058347,14
8,0.031333,0.031412,0.025160,0.042936,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.644591,0.529223,0.509301,0.632407,0.489931,0.561091,0.064529,18
9,0.025084,0.042784,0.049018,0.051015,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.661126,0.417083,0.664223,0.678337,0.619538,0.608062,0.097482,16
10,0.045922,0.039997,0.003126,0.006253,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.636028,0.479737,0.644883,0.646883,0.578696,0.597245,0.063859,17
11,0.024058,0.035568,0.027710,0.036753,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.706374,0.421865,0.662910,0.595381,0.685150,0.614336,0.103198,15
12,0.044147,0.035087,0.008053,0.007006,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.708322,0.645897,0.730573,0.699878,0.679078,0.692750,0.028657,6
13,0.006262,0.007669,0.036562,0.052686,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.638655,0.565349,0.709243,0.699920,0.712556,0.665145,0.056679,10
14,0.012505,0.006253,0.006249,0.007654,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.775623,0.425502,0.702176,0.677827,0.602419,0.636709,0.119213,11
15,0.015707,0.000153,0.025080,0.050160,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.622088,0.356094,0.744145,0.737004,0.714323,0.634731,0.145989,12
16,0.021957,0.012655,0.002069,0.004139,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.723754,0.644097,0.700815,0.727819,0.685661,0.696429,0.030351,5
17,0.012014,0.007700,0.010463,0.003190,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.756553,0.461375,0.698553,0.717801,0.716347,0.670126,0.106079,9

In [13]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:4
BMI:56
Children:5
Sex Male 0 or 1:5
Smoker Yes 0 or 1:3

In [14]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[44501.3982]

C:\Users\Rajesh\Anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  "X does not have valid feature names, but"